export const FETCH_ALL_PRODUCTS_PENDING = 'FETCH_ALL_PRODUCTS_PENDING';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_REJECTED = 'FETCH_ALL_PRODUCTS_REJECTED';
export const SINGLE_PRODUCTS_PENDING = 'SINGLE_PRODUCTS_PENDING';
export const SINGLE_PRODUCTS_SUCCESS = 'SINGLE_PRODUCTS_SUCCESS';
export const SINGLE_PRODUCTS_REJECTED = 'SINGLE_PRODUCTS_REJECTED';